"""
Generated by Postman Code

Collection: Customer Agent API
Collection UID: 42741317-38059bc2-0f38-4a21-bbbd-6eff1f1c0a58

Typed Python client for the Customer Agent FastAPI surface.
"""

from __future__ import annotations

from .chat.post_chat import post_chat
from .health.get_health import get_health
from .sessions.delete_session import delete_session
from .shared import (
    ApiError,
    ChatRequest,
    ChatResponse,
    ClearSessionResponse,
    HealthResponse,
)
from .variables import variables

__all__ = [
    "ApiError",
    "ChatRequest",
    "ChatResponse",
    "ClearSessionResponse",
    "CustomerAgentClient",
    "HealthResponse",
    "delete_session",
    "get_health",
    "post_chat",
    "variables",
]


class CustomerAgentClient:
    """Convenience wrapper around the generated endpoint functions."""

    def __init__(
        self,
        base_url: str | None = None,
        *,
        environment: str = "Customer Agent - Local",
        timeout: float = 60.0,
        chat_timeout: float = 120.0,
    ) -> None:
        env = variables.get(environment, {})
        collection = variables.get("collection", {})
        self.base_url = (
            base_url
            or env.get("baseUrl")
            or collection.get("baseUrl")
            or "http://127.0.0.1:8000"
        ).rstrip("/")
        self.default_session_id = env.get("session_id", "demo-session-1")
        self.timeout = timeout
        self.chat_timeout = chat_timeout

    def health(self) -> HealthResponse:
        return get_health(base_url=self.base_url, timeout=self.timeout)

    def chat(
        self,
        message: str,
        *,
        session_id: str | None = None,
    ) -> ChatResponse:
        return post_chat(
            base_url=self.base_url,
            session_id=session_id or self.default_session_id,
            message=message,
            timeout=self.chat_timeout,
        )

    def clear_session(self, session_id: str | None = None) -> ClearSessionResponse:
        return delete_session(
            base_url=self.base_url,
            session_id=session_id or self.default_session_id,
            timeout=self.timeout,
        )
