"""
Generated by Postman Code

Collection: Customer Agent API
Collection UID: 42741317-38059bc2-0f38-4a21-bbbd-6eff1f1c0a58
"""

from __future__ import annotations

variables: dict[str, dict[str, str]] = {
    "collection": {
        "baseUrl": "http://127.0.0.1:8000",
    },
    "Customer Agent - Local": {
        "baseUrl": "http://127.0.0.1:8000",
        "session_id": "demo-session-1",
    },
}
