"""
Generated by Postman Code

Collection: Customer Agent API
Collection UID: 42741317-38059bc2-0f38-4a21-bbbd-6eff1f1c0a58

Request: Sessions > DELETE Session
Request UID: 42741317-b233719c-b34c-12d3-95aa-f56bf510ad24
Request modified at: 2026-07-22T07:54:34.000Z
"""

from __future__ import annotations

from ..shared.http import encode_path_segment, join_url, request_json
from ..shared.types import ClearSessionResponse


def delete_session(
    *,
    base_url: str,
    session_id: str,
    timeout: float = 60.0,
) -> ClearSessionResponse:
    """Clear SQLite session state for the given ``session_id``."""
    path = f"/sessions/{encode_path_segment(session_id)}"
    url = join_url(base_url, path)
    payload = request_json("DELETE", url, timeout=timeout)
    return ClearSessionResponse.from_dict(payload or {})
