"""
Generated by Postman Code

Collection: Customer Agent API
Collection UID: 42741317-38059bc2-0f38-4a21-bbbd-6eff1f1c0a58

Request: Chat > POST Chat
Request UID: 42741317-0de635f8-68aa-fb14-79d3-e21847632533
Request modified at: 2026-07-22T07:54:35.000Z
"""

from __future__ import annotations

from ..shared.http import join_url, request_json
from ..shared.types import ChatRequest, ChatResponse


def post_chat(
    *,
    base_url: str,
    session_id: str,
    message: str,
    timeout: float = 120.0,
) -> ChatResponse:
    """
    Chat with CustomerServiceBot.

    Same ``session_id`` continues the conversation. Response includes answer,
    sources, images, clarify_options, route, and strategy.
    """
    url = join_url(base_url, "/chat")
    body = ChatRequest(session_id=session_id, message=message).to_dict()
    payload = request_json("POST", url, body=body, timeout=timeout)
    return ChatResponse.from_dict(payload or {})
