"""
Generated by Postman Code

Collection: Customer Agent API
Collection UID: 42741317-38059bc2-0f38-4a21-bbbd-6eff1f1c0a58

Request: Health > GET Health
Request UID: 42741317-b6d11568-7b47-d374-5daf-c56462baf89a
Request modified at: 2026-07-22T07:54:34.000Z
"""

from __future__ import annotations

from ..shared.http import join_url, request_json
from ..shared.types import HealthResponse


def get_health(*, base_url: str, timeout: float = 60.0) -> HealthResponse:
    """Health check — envelope data includes ``status`` and optional ``redis``."""
    url = join_url(base_url, "/health")
    payload = request_json("GET", url, timeout=timeout)
    return HealthResponse.from_dict(payload or {})
